# Site Settings
locale                   : "en-US"
title                    : "Mahammad Nabizade"
title_separator          : "-"
name                     : &name "Mahammad Nabizade"
description              : &description "Computer Vision PhD Student | Fall Detection & Action Recognition"
url                      : https://nmahammad.github.io
baseurl                  : ""
repository               : "nmahammad/nmahammad.github.io"
teaser                   : 
breadcrumbs              : false
words_per_minute         : 160

# Comments
comments:
  provider               : false

# Atom feed
atom_feed:
  path                   : 

# SEO Related
google_site_verification : 

# Social Sharing
twitter:
  username               : &twitter "GradientFlow13"

social:
  type                   : Person
  links:
    - "https://twitter.com/GradientFlow13"
    - "https://github.com/nmahammad"
    - "https://www.linkedin.com/in/mahammad-nabizade/"

# Analytics
analytics:
  provider               : false

# Site Author
author:
  name             : "Mahammad Nabizade"
  avatar           : "profile.png"
  bio              : "Computer Vision PhD Student & Research Engineer<br>Université Marie et Louis Pasteur"
  location         : "Besançon, France"
  employer         : "Université Marie et Louis Pasteur"
  email            : "mahammad.nabizade@univ-fcomte.fr"
  uri              : "https://nmahammad.github.io"
  github           : "nmahammad"
  linkedin         : "mahammad-nabizade"
  twitter          : *twitter
  google_scholar   : "https://scholar.google.com/citations?user=2Q85l2IAAAAJ&hl=en"
  orcid            : 

# Reading Files
include:
  - .htaccess
  - _pages
  - "*.pdf"

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - Gemfile
  - LICENSE
  - node_modules
  - package.json
  - README
  - tmp

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Europe/Paris

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
